# Site settings
title: Code Blog
email: kyle@kylefitch.com
description: "Ideas and thoughts on code projects that interest me."
baseurl: ""
url: "http://blog.kylefitch.com"
twitter_username: kyleFitch
github_username:  kylefitch

# Build settings
markdown: kramdown
